# Generated by Django 5.0.7 on 2024-08-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthentication',
            name='used_at',
            field=models.DateTimeField(null=True),
        ),
    ]
